Traceback (most recent call last):
  File "/home/henry/Work/phd-work/vibronic-dimer/QHE_notes_figures.py", line 262, in <module>
    PARAMS =  data_maker(100., 0., 20, 50, 1., 0., 0., 2, 1, '2a', 1,  make_new_data=True)
  File "/home/henry/Work/phd-work/vibronic-dimer/QHE_notes_figures.py", line 211, in data_maker
    del DATA_J
UnboundLocalError: local variable 'DATA_J' referenced before assignment

