Traceback (most recent call last):
  File "/home/henry/Work/phd-work/vibronic-dimer/QHE_notes_figures.py", line 265, in <module>
    PARAMS = data_maker(100., 20., 20, 50, 1., 0., 0., 2, 3, '2b', 1, make_new_data=True)
  File "/home/henry/Work/phd-work/vibronic-dimer/QHE_notes_figures.py", line 215, in data_maker
    make_new_data=make_new_data)
  File "/home/henry/Work/phd-work/vibronic-dimer/QHE_notes_figures.py", line 122, in named_plot_creator
    ax2.plot(timelist, J_DATA.expect[6].real, linestyle='--')
UnboundLocalError: local variable 'ax2' referenced before assignment

